import bcrypt from 'bcryptjs';


//"Statiskie" noklusējuma dati - pirms dinamisko datu izveides MongoDB datubāzē 
const data = {
    users:[
        {
        name: 'Rihards',
        email: 'rihards@gmail.com',
        password: bcrypt.hashSync('123456', 16),
        isAdmin: true,
        },
        {
            name: 'Jānis',
            email: 'janis@gmail.com',
            password: bcrypt.hashSync('123456', 16),
            isAdmin: false,
        },
    ],
    products:[
    {
        name: 'Apple iPhone 12 Pro Max',
        category: 'Viedtālruņi',
        image: '/images/4.jpg',
        price: 1199,
        brand: 'Apple',
        rating: 0,
        numReviews: 0,
        countInStock: 30,
        description: '5G kļūst Pro. A14 Bionic iet garām jebkurai citai viedtālruņa mikroshēmai. Pro kameru sistēma paaugstina fotografēšanu vājā apgaismojumā - īpaši iPhone 12 Pro Max modelī. Un Ceramic Shield nodrošina četras reizes labāku izturību pret kritieniem. iPhone viedtālrunī jau bija visizturīgākais stikls. Tāpēc, lai dramatiski palielinātu iPhone 12 Pro izturību, mums bija jāievieš pilnīgi jauns materiāls. 5G pārveido iPhone ar uzlabotu bezvadu ātrumu un labāku sniegumu pārslogotajos tīklos. Tagad varat lejupielādēt milzīgus failus, atrodoties ceļā, vai straumēt augstas kvalitātes HDR filmas. Bez. Aiz. Ķer. Šanās! iPhone ir arī visvairāk viedtālruņu 5G joslu, tāpēc jūs saņemat 5G vairāk valstīs. Un viss šis ātrums paver pārsteidzošas iespējas lietotņu nākotnei.',
    },
    {
        name: 'Apple Watch Series 5',
        category: 'Viedpulksteņi',
        image: '/images/appw1.jpg',
        price: 399,
        brand: 'Apple',
        rating: 0,
        numReviews: 0,
        countInStock: 7,
        description: 'Pieskati savu veselību. Fiksē treniņu datus. Gūsti visu vajadzīgo motivāciju, lai sasniegtu sportošanas mērķus. Un turies sakaros – gan ar sev svarīgajiem cilvēkiem, gan informāciju. Ar Apple Watch Series 5 tas viss ir pa rokai. Trīs riņķi. Viens mērķis. Stand, Move un Exercise riņķi ir vizualizācija tam, kā un cik tu kusties ik dienu. Noskaidro, vai nesēdi par daudz. Nosaki, cik kaloriju sadedzināji. Piefiksē, cik minūtes velti sportam. Vari pat lepni atrādīt savus riņķus draugiem. Izmēģini jaunās aktivitātes sacensības un saņem uzmundrinājumus no gudrās treniņu sistēmas, kad tev tie visvairāk vajadzīgi. Fiksē sasniegto tādās populārās nodarbēs kā joga, riteņbraukšana, peldēšana un augstas intensitātes intervāla treniņi.1 Fiksē datus par skrējieniem ar tādām mūsdienīgām funkcijām kā kadence un paziņojumi par tempu. Savieno savu pulksteni ar saderīgu sporta zāles aprīkojumu – bez kādiem vadiem.2 Un sinhronizē mīļāko atskaņošanas sarakstu no Apple Music, lai rokas nekad nenolaistos.',
    },
    {
        name: 'Huawei P30 Lite 128GB',
        category: 'Viedtālruņi',
        image: '/images/p30.jpg',
        price: 204,
        brand: 'Huawei',
        rating: 0,
        numReviews: 0,
        countInStock: 10,
        description: 'Paplašini savu perspektīvu ar HUAWEI P30 lite 120° īpaši plata leņķa objektīvu3 un iemūžini plašas ainavas satriecošos attēlos, kuros nekas nav palicis ārpus kadra. Ķer kadrus bez ierobežojumiem. Uzlabo savus fotoattēlus ar jaudīgo MI ainu atpazīšanas tehnoloģiju. HUAWEI P30 lite priekšējā kamera var atpazīt vairāk nekā 8 kategorijas reāllaikā, savukārt aizmugurējā kamera var atpazīt 22 dažādas kategorijas. Iestatījumi, piemēram, krāsas, apgaismojums un kontrasts, tiek automātiski pielāgoti žilbinošu fotoattēlu iegūšanai. Stilīgais un ērtais HUAWEI P30 lite komfortabli ieguls plaukstā. Plānā 3D izliektā stikla konstrukcija veidota tā, lai būtu ērti satverama un lietojama ar vienu roku. Pieejamas trīs krāsas, tostarp ar vizuāli pievilcīgo zaigojošas un pakāpeniskas krāsu pārejas apdari. Pieejamā atmiņa: 4 GB + 128 GB HUAWEI P30 lite uzlabotā RAM un krātuve nozīmē to, ka iemīļotajām lietām būs vairāk vietas. Novērtē lielāko atmiņas pielāgojamību saturam vai failiem, ko izmanto ikdienā, piemēram, mūzikai, fotoattēliem, videofailiem un lietotnēm',
    },
    {
        name: 'iPhone 12 mini 128GB',
        category: 'Viedtālruņi',
        image: '/images/iphone12.jpg',
        price: 899,
        brand: 'Apple',
        rating: 0,
        numReviews: 0,
        countInStock: 15,
        description: '5G kļūst Pro. A14 Bionic iet garām jebkurai citai viedtālruņa mikroshēmai. Pro kameru sistēma paaugstina fotografēšanu vājā apgaismojumā - īpaši iPhone 12 Pro Max modelī. Un Ceramic Shield nodrošina četras reizes labāku izturību pret kritieniem. iPhone viedtālrunī jau bija visizturīgākais stikls. Tāpēc, lai dramatiski palielinātu iPhone 12 Pro izturību, mums bija jāievieš pilnīgi jauns materiāls. 5G pārveido iPhone ar uzlabotu bezvadu ātrumu un labāku sniegumu pārslogotajos tīklos. Tagad varat lejupielādēt milzīgus failus, atrodoties ceļā, vai straumēt augstas kvalitātes HDR filmas. Bez. Aiz. Ķer. Šanās! iPhone ir arī visvairāk viedtālruņu 5G joslu, tāpēc jūs saņemat 5G vairāk valstīs. Un viss šis ātrums paver pārsteidzošas iespējas lietotņu nākotnei.',
    },
    {
        name: 'iPhone 12 128GB',
        category: 'Viedtālruņi',
        image: '/images/iphone12b.jpg',
        price: 939,
        brand: 'Apple',
        rating: 0,
        numReviews: 0,
        countInStock: 15,
        description: '5G kļūst Pro. A14 Bionic iet garām jebkurai citai viedtālruņa mikroshēmai. Pro kameru sistēma paaugstina fotografēšanu vājā apgaismojumā - īpaši iPhone 12 Pro Max modelī. Un Ceramic Shield nodrošina četras reizes labāku izturību pret kritieniem. iPhone viedtālrunī jau bija visizturīgākais stikls. Tāpēc, lai dramatiski palielinātu iPhone 12 Pro izturību, mums bija jāievieš pilnīgi jauns materiāls. 5G pārveido iPhone ar uzlabotu bezvadu ātrumu un labāku sniegumu pārslogotajos tīklos. Tagad varat lejupielādēt milzīgus failus, atrodoties ceļā, vai straumēt augstas kvalitātes HDR filmas. Bez. Aiz. Ķer. Šanās! iPhone ir arī visvairāk viedtālruņu 5G joslu, tāpēc jūs saņemat 5G vairāk valstīs. Un viss šis ātrums paver pārsteidzošas iespējas lietotņu nākotnei.',
    },
    {
        name: 'Samsung SM-G780 Galaxy S20',
        category: 'Viedtālruņi',
        image: '/images/S20.jpg',
        price: 569,
        brand: 'Samsung',
        rating: 0,
        numReviews: 0,
        countInStock: 20,
        description: 'Šis ir tālrunis tiem, kuri gatavi visam. Mēs ieklausījāmies jūsu vēlmlēs un radījām tālruni bez kompromisiem. Šis ir tālrunis, kas īpaši pielāgots ikvienam. Tāpēc neatkarīgi no tā, vai Tu esi fotogrāfijas, spēļu vai iedvesmojoša satura fans, mēs esam radījuši unikālu S20 inovāciju kombināciju. Šis tālrunis sniedz Tev to, ko Tu vēlies, lai Tu varētu darīt to, ko vēlies visvairāk. Toņi, kas pārsteigs pat varavīksni Tavs tālrunis gandrīz vienmēr ir tavās rokās, tāpēc tam nevainojami jāpapildina Tavs stils. Izvēlies no plašā, modernā krāsu klāsta ar elegantu matētu apdari, sākot no lieliem un uzkrītošiem un beidzot ar klasiskiem telefoniem. INFINITY-O DISPLEJS Visa uzmanība ir pievērsta bezgalīgajam-O displejam. Uzlabo savu redzesleņķi. Infinity-O Full HD+ 6,5 collu displejam ir tikko manāmas maliņas un ļoti sīks kameras atvērums. Tādējādi tu vari ienirt ekrānā, kas padara spēļu spēlēšanu, straumēšanu un video zvanus īpaši jautru.',
    },
    {
        name: 'Huawei Watch GT2 Sport',
        category: 'Viedpulksteņi',
        image: '/images/huaweiwatch.jpg',
        price: 569,
        brand: 'Huawei',
        rating: 0,
        numReviews: 0,
        countInStock: 13,
        description: 'HUAWEI WATCH GT 2 atbalstot GPS un GLONASS satelīta pozicionēšanas sistēmas un nodrošina precīzus un ātrākus pozicionēšanas pakalpojumus. Pēc pārgājiena vai maratona jūs precīzi zināsiet, kur esat, un savu aktivitātes progresu. HUAWEI TruSeen™ 3.5 nodrošina efektīvāku un precīzāku sirdsdarbības mērīšanu reāllaikā. Kopā ar mākslīgā intelekta sirdsdarbības algoritmu tas uzrauga sirdsdarbības ātrumu visu dienu, pat guļot. Pateicoties 5 ATM ūdensnecaurlaidīgajai funkcijai, HUAWEI WATCH GT 2 var monitorēt sirdsdarbības ātrumu, kamēr peldējāt2, kā arī SWOLF rezultātus, attālumu, sadedzinātās kalorijas un ātrumu.',
    },
    {
        name: 'Apple AirPods Gen 2 In-Ear White',
        category: 'Viedierīču aksesuāri',
        image: '/images/airpods.jpg',
        price: 144,
        brand: 'Apple',
        rating: 0,
        numReviews: 0,
        countInStock: 16,
        description: 'Ar ilgāku sarunu laiku un jauno bezvadu uzlādes kārbiņu AirPods bezvadu austiņu lietošana ir kļuvusi par vēl nebijušu piedzīvojumu. Vienkārši izņem tās no kārbiņas un sāc lietot ar visām savām ierīcēm. Ieliec tās ausīs, un tās vienā mirklī izveidos savienojumu, radot ap tevi bagātīgu augstas kvalitātes skaņas telpu. Patiešām brīnumaini. Bezvadu pilnība. Viens vienīgs pieskāriens, un AirPods ir ieslēgtas, iestatītas un savienotas.1 Tikpat vienkārša ir arī to lietošana. Tās spēj sajust, kad ir tavās ausīs, un ieturēt pauzi, kad tās izņem. Klausies no sava iPhone, iPad vai Mac – AirPods skaņa vienmēr būs lieliska. Jauda, ko gribas dzirdēt. AirPods darbina Apple H1 austiņu procesors. Un tāpēc to bezvadu savie­nojums ar tavām ierīcēm ir ātrāks un stabilāk – tās līdz 2x ātrāk pārslēdzas starp aktīvām ierīcēm2 un tālruņa zvanu savie­nojums ir 1,5x ātrāks.3 Lai ko tu darītu – spēlētu spēles, klausītos mūziku vai baudītu podkāstus – tevi priecēs augstākas kvalitātes skaņa.',
    },
    {
        name: 'Apple MacBook Pro 13.3" Retina M1 256GB Silver',
        category: 'Datori',
        image: '/images/mac.jpg',
        price: 1402,
        brand: 'Apple',
        rating: 0,
        numReviews: 0,
        countInStock: 12,
        description: 'Apple M1 mikroshēma nodrošina 13 collu MacBook Pro ātrumu un neticamu jaudu. Ar līdz 2,8x centrālā procesora veiktspēju. Līdz 5 reizes lielāks par grafiskās kartes ātrumu. Mūsu vismodernākais neironu dzinējs, kas nodrošina 11x ātrāku mašīnmācīšanos. Akumulatora darbības laiks līdz 20 stundām - visilgākais no visiem Mac datoriem. Tā ir mūsu vispopulārākais Pro piezīmjdators, kas ir pacelts pilnīgi jaunā līmenī.',
    },
    {
        name: 'Apple MacBook Pro 16 Silver i7 16GB 512GB',
        category: 'Datori',
        image: '/images/mac1.jpg',
        price: 2499,
        brand: 'Apple',
        rating: 0,
        numReviews: 0,
        countInStock: 11,
        description: 'Jaunais MacBook Pro ir visu laiku jaudīgākais Apple portatīvais dators, kas radīts tiem, kuri paplašina robežas un maina pasauli. Iespaidīgs 16 collu Retina displejs, superātri procesori, nākamās paaudzes grafika, visu laiku ietilpīgākais MacBook Pro akumulators, jauna Magic Keyboard tastatūra un apjomīga datu krātuve – īstens Pro portatīvais īsteniem pro lietotājiem.',
    },
    {
        name: 'Apple MacBook Pro 16 Space Gray i9 16GB 1000 SSD',
        category: 'Datori',
        image: '/images/mac2.jpg',
        price: 2999,
        brand: 'Apple',
        rating: 0,
        numReviews: 0,
        countInStock: 9,
        description: 'MacBook Pro Jaudīgākais. Jaudī­gākajiem. Jaunais MacBook Pro ir visu laiku jaudīgākais Apple portatīvais dators, kas radīts tiem, kuri paplašina robežas un maina pasauli. Iespaidīgs 16 collu Retina displejs, superātri procesori, nākamās paaudzes grafika, visu laiku ietilpīgākais MacBook Pro akumulators, jauna Magic Keyboard tastatūra un apjomīga datu krātuve – īstens pro portatīvais īsteniem pro lietotājiem. Retina displejs Liela, skaista darbavieta. Lieliem, skaistiem sasniegumiem. Jaunā MacBook Pro satriecošais 16 collu Retina displejs ir lielākais Retina displejs, kāds jebkad pieredzēts Mac portatīvajos. Ar 500 nitu spilgtumu baltie toņi ir žilbinoši spoži, savukārt melnie toņi – piesātināti dziļi, pateicoties precīzai šķidro kristālu molekulu foto līdzināšanai. Un plašais P3 krāsu spektrs nodrošina krāšņus un precīzus toņus attēliem un video. Tādēļ, lai kur tu būtu, savu veikumu redzēsi labākajā gaismā.',
    },
    {
        name: 'Asus VivoBook S14 S433EA-EB130',
        category: 'Datori',
        image: '/images/asus.jpg',
        price: 786,
        brand: 'Asus',
        rating: 0,
        numReviews: 0,
        countInStock: 9,
        description: 'ASUS VivoBook, ilggadējs favorīts, iegūst jaunu drosmīgāku izskatu, kas noteikti iegūs impulsus. Plānajam un vieglajam VivoBook S14 tagad ir dimanta griezuma malas un faktūras apdare, un tas ir pieejams četrās atšķirīgās krāsās, kas ir izvēlētas, lai atspoguļotu jūsu personību. Pozitīvās vibrācijas turpinās, kad atverat vāku, kur jūs sagaida Enter taustiņš ar krāsām bloķējošām malām. VivoBook S14 izceļ patieso jūs gan iekšpusē, gan ārpusē. Gludais VivoBook S14 izceļas ar teksturētu metāla šasiju ar dimanta griezuma malām, unikālām krāsām un krāsu bloķējošu Enter taustiņu. Dimanta griezuma dizains arī atvieglo vāka atvēršanu. Neatkarīgi no tā, vai esat satura veidotājs vai vienkārši izmantojat VivoBook S14 kā ikdienas klēpjdatoru, VivoBook S14 ir sniegums, kas jums nepieciešams. To darbina 10. paaudzes Intel® Core i7 procesoram ar atmiņu līdz 16 GB. Lielas ietilpības PCIe® SSD nodrošina īpaši ātru krātuvi, lai ātri piekļūtu vajadzīgajam.',
    },
    {
        name: 'Datorspēļu pele Logitech G102 Lightsync Black',
        category: 'Datoru perifērijas ierīces',
        image: '/images/log.jpg',
        price: 39,
        brand: 'Logitech',
        rating: 0,
        numReviews: 0,
        countInStock: 30,
        description: 'Izmantojiet spēles laiku maksimāli, izmantojot G102 spēļu peli, kas aprīkota ar LIGHTSYNC tehnoloģiju, spēles līmeņa sensoru un klasisku 6 pogu dizainu. Izgaismojiet savu spēli ... un savu galdu. Izvēlieties kādu no dinamiskām animācijām, spēļu un multivides iestatījumiem vai ieprogrammējiet pats savu krāsu aptuveni no 16,8 miljoniem krāsu Izvēlieties vienu krāsu, sajauciet trīs, izvēlieties jautru animācijas iestatījumu vai izveidojiet pats savu. Izvēle ir tava! Jūs pat varat sinhronizēt peli ar citiem Logitech G LIGHTSYNC pārnesumiem, lai tā būtu ideāli piemērota. Iestatiet apgaismojumu uz Screen Sampler, lai tas sinhronizētos ar jūsu ekrānu. Iestatiet peli, lai reaģētu uz krāsu maiņu spēlēs, filmās un citur. Spēlējiet mūziku, filmas, spēles - jebkura skaņa un G102 mirgos krāsās. Pielāgojiet līmeņus un krāsas, lai padarītu deju ballīti visu savu.',
    },
    {
        name: 'Datorpele Logitech M185 Grey, bezvadu, optiskā',
        category: 'Datoru perifērijas ierīces',
        image: '/images/log1.jpg',
        price: 17,
        brand: 'Logitech',
        rating: 0,
        numReviews: 0,
        countInStock: 30,
        description: 'Vienkārša, uzticama pele ar Plug-and-play tehnoloģijas bezvada pieslēgumu un 1 gadu bateriju darbības laiku, kā arī 3 gadu ierobežotu garantiju. Darbojas datoros ar Windows® un Mac® operētājsistēmām. Uztverējs ir tik mazs un nemanāms, ka, pieslēdzot to USB portam, Jūs to varat atstāt tur pat. Vairāk nevajag raizēties, ka tas varētu pazust. Jūs varat strādāt veselu gadu, nemainot baterijas. Barošanas slēdzis un automātiska pāreja miega režīmā ļauj samazināt enerģijas patēriņu. Jūs varēsiet novērtēt pasaules vadošā peļu ražošanas uzņēmuma Logitech ražotās produkcijas augstu kvalitāti un uzticamību, kā ari trīs gadu garantijas priekšrocības. Pieslēgums ar ātrgaitas datu pārraidi gandrīz bez kavējumiem un zaudējumiem, kas apvieno vadu savienojuma drošību un bezvadu ērtumu un brīvību. Nekādas programmatūras, nekādu problēmu. Vienkārši pieslēdziet nano uztvērēju datora portam un uzreiz ķeraties darbam. Ergonomiska uzbūve nodrošina komfortu, turot peli gan ar labo, gan ar kreiso roku. Darboties ar to ir daudz ertāk, nekā ar klēpjdatora skārienpalikni. Pele darbojas ar Windows, Mac un Linux®. Neatkarīgi no tā, ar kādu datoru Jūs strādājat šodien vai kādu nopirksiet rīt - šī pele vienmēr darbosies kā vajag.',
    },
    {
        name: 'Datorspēļu pele Logitech G Pro Black, bezvadu, optiskā',
        category: 'Datoru perifērijas ierīces',
        image: '/images/log2.jpg',
        price: 110,
        brand: 'Logitech',
        rating: 0,
        numReviews: 0,
        countInStock: 26,
        description: 'PRO Wireless tika izstrādāta kā galvenā spēļu pele esporta profesionāļiem. Divu gadu laikā Logitech G sadarbojās ar vairāk nekā 50 profesionāliem spēlētājiem, lai atrastu perfektu formu, svaru un sajūtu, apvienojot to ar mūsu LIGHTSPEED bezvadu un HERO 25k sensoru tehnoloģijām. Rezultāts ir spēļu pele ar nepārspējamu veiktspēju un precizitāti, kas dod jums rīkus un pārliecību, kas nepieciešama uzvarai. Ar HERO 25K, nākamās paaudzes spēļu sensora izgudrojumu, pasaulei tagad ir jauns līderis. Programmai PRO Wireless HERO 25K ir optimizēts, lai izsekotu nenormālus kustības ar ātrumu, kas pārsniedz 400 IPS, neizgriežoties. HERO 25K nodrošina maksimālu veiktspēju ar jebkuru jutību ar nulles izlīdzināšanu, paātrinājumu vai filtrēšanu no 100 līdz 25 600 DPI.',
    },
    {
        name: 'Spēļu tastatūra Logitech G815 GL Clicky',
        category: 'Datoru perifērijas ierīces',
        image: '/images/log3.jpg',
        price: 175,
        brand: 'Logitech',
        rating: 0,
        numReviews: 0,
        countInStock: 18,
        description: 'Uzlabotas spēļu tehnoloģijas izsmalcinātā īpaši plānā dizainā. Pilnībā pielāgojams, aprīkots ar LIGHTSYNC RGB un īpašām G taustiņām. Izstrādāts augstas veiktspējas spēlēšanai ar zema profila GL mehāniskajiem slēdžiem klikšķu, taustes un lineārajās variācijās. Pieredze G815 un spēlē nākamo dimensiju. G815 ir inženierzinātņu un dizaina varoņdarbs ar neticami izsmalcinātu, neiespējami plānu struktūru bez kompromisiem attiecībā uz veiktspēju vai funkciju kopumu. Izturīgs, ērts un gatavs intensīvām spēļu sesijām, G815 ir patiesi nākamās paaudzes spēļu mehāniskās tastatūras. Iegūstiet ātrumu, precizitāti un veiktspēju pusi no tradicionālo slēdžu augstuma. Zema profila GL mehāniskie slēdži tiek stingri pārbaudīti, lai tie atbilstu stingrām izturības, reaģēšanas un precizitātes prasībām. Pieejami trīs slēdžu veidi: GL Clicky - dzirdama klikšķu un taustes atgriezeniskā saite, GL taustāms - maigs trieciens dažām taustes atsauksmēm, GL Lineārs - pilnīgi vienmērīgs taustiņa taustiņš.',
    },
    {
        name: 'Logitech Wireless Keyboard K270',
        category: 'Datoru perifērijas ierīces',
        image: '/images/log4.jpg',
        price: 30,
        brand: 'Logitech',
        rating: 0,
        numReviews: 0,
        countInStock: 48,
        description: 'Uzticams bezvadu savienojums - visur, kur izmantojat tastatūru - pateicoties Logitech Unifying uztvērējam, kas savieno pārī līdz pat sešām ar Unifying saderīgām pelēm un tastatūrām. Mazais bezvadu uztvērējs paliek jūsu klēpjdatorā - pārvietojoties nav nepieciešams to atvienot, un savieno tastatūru. Tātad jūs varat strādāt vai spēlēt vairāk vietās, piemēram, ērtajā dīvānā, un bezvadu savienojums faktiski novērš aizkavēšanos, pamešanu un traucējumus un nodrošina līdz pat 10 metru (33 pēdu) diapazonu. Jūs izbaudīsit mazāk problēmu, ja akumulatora darbības laiks ir līdz 24 mēnešiem. ** Automātiskais gaidstāves režīms palīdz ietaupīt enerģiju. Visvairāk darāmās lietas ir tieši jūsu rokai, izmantojot astoņus karstos taustiņus, kas nodrošina tūlītēju piekļuvi internetam, e-pastu, atskaņošanu / pauzi, skaļumu un daudz ko citu. Iestatīšana prasa sekundes - jūs vienkārši pievienojat bezvadu uztvērēju datora USB portam un nekavējoties sākat izmantot tastatūru bez programmatūras. Gludā tastatūra ietaupa jūsu vietu, nezaudējot komfortu, pateicoties pazīstamajam, pilna izmēra izkārtojumam - ieskaitot ciparu tastatūru - un platai, izliektai atstarpes joslai. Šķidrums izplūst no tastatūras, tāpēc jums nav jāuztraucas par investīciju sabojāšanu ar nejaušām noplūdēm. Jūs saņemat augsto kvalitāti un uzticamību, kas padara Logitech par pasaules līderi tastatūrām par cenu, ko varat atļauties, kā arī 3 gadu ierobežotu aparatūras garantiju. Īpašais pārklājums aizsargā taustiņus no izbalēšanas, lai jūs varētu redzēt, ko rakstāt nākamajos gados.',
    },
    {
        name: 'Kingston HyperX Alloy FPS Pro',
        category: 'Datoru perifērijas ierīces',
        image: '/images/kingston.jpg',
        price: 59,
        brand: 'Kingston',
        rating: 0,
        numReviews: 0,
        countInStock: 48,
        description: 'HyperX ™ Alloy ir paredzēts FPS spēlētājiem, kuri vēlas uzticamu, precīzu tastatūru, lai maksimāli palielinātu darbvirsmas vietu. Šī 87 taustiņu tastatūra nodrošina visu, kas nepieciešams profesionālam spēlētājam, bet bez ciparu tastatūras. Sakausējums ir pieejams ar uzticamiem, atsaucīgiem taustiņu slēdžiem CHERRY® MX Blue vai Red1, un tā izturīgais cietā tērauda rāmis nodrošina stabilu platformu spēļu svarīgākajās daļās. Īpaši minimālais dizains un noņemamais kabelis padara tastatūru ļoti pārnēsājamu, taču tā joprojām ir aprīkota ar funkcijām; Spēles režīms, 100% Anti-Ghosting, N-Key apgāšanās un HyperX sarkanais apgaismojums un dinamiskie efekti, lai uzsvērtu jūsu sistēmas stilu.',
    },
    {
        name: 'Bezvadu austiņas JBL T500BT Black',
        category: 'Datoru perifērijas ierīces',
        image: '/images/jbl.jpg',
        price: 34,
        brand: 'JBL',
        rating: 0,
        numReviews: 0,
        countInStock: 25,
        description: 'JBL TUNE500BT austiņas ļauj straumēt spēcīgu skaņu bez piestiprinātām virknēm līdz pat 16 stundām tīra prieka. Šīs austiņas ir viegli lietojamas un aprīkotas ar 32 mm JBL draiveriem un JBL Pure Bass skaņu, un tās katru reizi nodrošina ērtu piekļuvi lieliskai skaņai. Un, ja zvans ienāk, kamēr skatāties videoklipu citā ierīcē, JBL TUNE500BT vienmērīgi pārslēdzas uz jūsu mobilo tālruni. Bluetooth iespējotas un ērtas, JBL TUNE500BT austiņas ļauj arī izveidot savienojumu ar Siri vai Google Now, neizmantojot mobilo ierīci. JBL TUNE500BT austiņas ir pieejamas 4 svaigās krāsās un ir saliekamas, lai tās būtu ērti pārnēsājamas.',
    },
    {
        name: 'Bezvadu austiņas Apple AirPods Pro White',
        category: 'Datoru perifērijas ierīces',
        image: '/images/airpod2.jpg',
        price: 289,
        brand: 'Apple',
        rating: 0,
        numReviews: 0,
        countInStock: 28,
        description: 'AirPods Pro ir noturīgas pret sviedriem un mitrumu un paredzētas izmantošanai treniņos un ar ūdeni nesaistītos sporta veidos. AirPods Pro tika pārbaudītas kontrolētos laboratorijas apstākļos un ir ieguvušas IEC standartam 60529 atbilstošu novērtējumu IPX4. Noturīgums pret sviedriem un mitrumu nav nemainīgs un var mazināties normāla nolietojuma dēļ. Nemēģini uzlādēt samirkušas AirPods Pro. Norādes par tīrīšanu un žāvēšanu meklē šeit: https://support.apple.com/kb/HT210711. Uzlādes kārbiņa nav noturīga pret sviedriem un mitrumu. Testēšanu veica Apple 2019. gada oktobrī, izmantojot pirmsizlaides AirPods Pro ar bezvadu uzlādes kārbiņu un programmatūru, kas savienotas pārī ar iPhone 11 Pro Max ierīcēm ar pirmsizlaides programmatūru.',
    },
    {
        name: 'Monitors MSI Optix G241VC, 23.6", 1 ms',
        category: 'Datoru monitori',
        image: '/images/msi.jpg',
        price: 154,
        brand: 'MSI',
        rating: 0,
        numReviews: 0,
        countInStock: 9,
        description: 'Optix G241VC izmanto augstas kvalitātes Samsung izliekto paneli ar daudzām īpašām spēlētāju īpašībām, kas viņiem palīdzēs izbaudīt brīnišķīgo spēļu pasauli. 178˚ platais skata leņķis ļauj dalīties aizraujošajā spēļu pieredzē ar apkārtējiem draugiem, radot gan jautras, gan spilgtas atmiņas. 1800R līknes paneļa dizains - vispiemērotākais cilvēka acīm. Patiesā krāsa - NTSC 85%, sRGB 110%. Platleņķa leņķis - redzams 178 °. Optimizēts ar MSI Gaming VGA - sniedzot jums vislabāko vizuālo pieredzi. AMD FreeSync - turiet ekrānu no ekrāna.',
    },
    {
        name: 'Asus TUF Gaming VG249Q, 23.8", 1 ms',
        category: 'Datoru monitori',
        image: '/images/asus1.jpg',
        price: 219,
        brand: 'Asus',
        rating: 0,
        numReviews: 0,
        countInStock: 16,
        description: '23,8 collu Full HD (1920x1080) IPS spēļu monitors ar ātru 144Hz atsvaidzes intensitāti, kas paredzēts profesionāliem spēlētājiem un ātrdarbīgu spēlēšanu Ietver ASUS Extreme Low Motion Blur (ELMB) tehnoloģiju ar 1ms MPRT, lai vēl vairāk samazinātu spoku un kustības aizmiglojumu FreeSync ™ tehnoloģija, lai novērstu ekrāna plīsumus un nemierīgus kadru ātrumus Piedāvā ergonomiski izstrādātu statīvu, kas piedāvā plašas pagriešanas, slīpuma, pagriešanās un augstuma regulēšanas iespējas Shadow Boost uzlabo attēla detaļas tumšos apgabalos, padarot ainas spilgtākas, nepietiekami eksponējot spilgtus apgabalus Atbalsta gan Adaptive-Sync ar NVIDIA GeForce * grafikas kartēm, gan FreeSync ar AMD Radeon grafiskajām kartēm * Savietojams ar NVIDIA GeForce GTX 10 sēriju, GTX 16 sēriju, RTX 20 sēriju un jaunākām grafikas kartēm Full HD (1920 X 1080) @ 120Hz izeja uz PS5 un Xbox Series X / S',
    },
    {
        name: 'Monitors AOC C24G1, 24", 1 ms',
        category: 'Datoru monitori',
        image: '/images/aoc.jpg',
        price: 219,
        brand: 'AOC',
        rating: 0,
        numReviews: 0,
        countInStock: 14,
        description: 'LED izgaismojums nodrošina augstu kontrastu, lielisku gaišumu un minimālu elektroenerģijas patēriņu, turklāt LED monitoru ekrāna korpuss ir daudz plānāks un elegantāks par vecākas tehnoloģijas izstrādājumiem. Pateicoties FullHD (1920px X 1080px) izšķirtspējai šis monitors lieliski kalpos BlueRay kvalitātes filmu baudīšanai pilna ekrāna režīmā. Par savietojamību ar mūsdienīgām grafiskajām kartēm un video atskaņotājiem parūpēsies HDMI ieeja. DisplayPort pieslēgvieta nodrošina augstākās kvalitātes attēla saņemšanu no datora grafiskās kartes, kas atbalsta šo tehnoloģiju. Pieslēgvieta D-SUB atbalsta grafiskās kartes ar iepriekšējās paaudzes - analgo VGA spraudni un salīdzinoši jaunākas paaudzes DVI-I standartu izmantojot pāreju DVI-I -> D-Sub. VA panelis šim monitoram piešķir augstus krāsu atbilstības rādītājus un uzlabotu skata leņķi. 1ms reakcijas laiks ir lieliski piemērots spēlēm un dinamiskām filmām.',
    },
    {
        name: 'Xiaomi Mi Smart Band 4C Black',
        category: 'Viedpulksteņi',
        image: '/images/xi.jpg',
        price: 17,
        brand: 'Xiaomi',
        rating: 0,
        numReviews: 0,
        countInStock: 47,
        description: 'Taisnstūra dizains ar 1,08 collu krāsu ekrānu Tagad Xiaomi mūs pārsteidz ar atjaunotu 4c aproces dizainu, kam ir maz sakara ar viņu jau labi zināmo aproces stilu. Tas mums vairāk atgādina Huawei Band 4 Pro vai Fitibit Charge, galvenokārt tā taisnstūra formas dēļ. Tam blakus ekrānam ir poga, kas ļauj to bloķēt vai atbloķēt, un jūs varat pārvietoties pa to, pieskaroties. Ekrāns ir pilnkrāsu TFT, kura izmērs ir 1,08 collas, un tā izšķirtspēja ir 220 x 128 un 200 nitu spilgtums, tāpēc visu informāciju varat redzēt īsumā un ar atbilstošu spilgtuma līmeni. Protams, tās klasiskā silikona siksna atgriežas kopā ar Xiaomi Mi Smart Band 4c, tāpēc to var ērti valkāt ilgu laiku, īpaši sportojot. Tomēr nepalaidiet garām mūsu piederumu kategoriju, kur varat atrast dažāda veida siksnas, kas ļauj to pielāgot elegantākiem gadījumiem.',
    },
    {
        name: 'Huawei Honor Magic Watch 2 42mm Black',
        category: 'Viedpulksteņi',
        image: '/images/huawei1.jpg',
        price: 129,
        brand: 'Huawei',
        rating: 0,
        numReviews: 0,
        countInStock: 12,
        description: 'MagicWatch 2 korpuss ir izgatavots no rafinēta 316L nerūsējošā tērauda - bieži izmantots materiāls aviācijas un kosmosa industrijā, piedāvājot augstu izturības un svara attiecību un mazāku uzņēmību pret ikdienas darbību radītajiem iespiedumiem un skrāpējumiem. Laiks īsumā. Vienmēr ieslēgts displejs Vienmēr ieslēgtais AMOLED displejs paliek izgaismots, lai tajā brīdī varētu paskatīties, kamēr ekrānam nav vajadzīgs laiks, lai to izgaismotu. Akumulatora veiktspējas sasniegums līdz 7 dienām Izmantojiet visu savu sniegumu 24/7. MagicWatch 2, ko nodrošina pilnīgi jaunais HUAWEI Kirin A1 mikroshēmojums, ātrāk apstrādā datus, vienādiem rezultātiem izmantojot mazāk enerģijas. Galvenais treniņu un veselības guru. 15 mērķa fitnesa režīmi Esiet motivēts ceļā uz savu mērķu sasniegšanu. MagicWatch 2 fitnesa režīmiem ir balss vadība4, lai saņemtu reāllaika padomus. Vakarā atpūtieties un veltiet minūti atpūtai, izmantojot elpošanas lietotni, lai labāk gulētu naktī.',
    },
    {
        name: 'Apple Watch Series 3 38mm GPS Silver/White',
        category: 'Viedpulksteņi',
        image: '/images/appw.jpg',
        price: 215,
        brand: 'Apple',
        rating: 0,
        numReviews: 0,
        countInStock: 18,
        description: 'Pieskati savu veselību. Fiksē treniņu datus. Gūsti visu vajadzīgo motivāciju, lai sasniegtu sportošanas mērķus. Un turies sakaros – gan ar sev svarīgajiem cilvēkiem, gan informāciju. Ar Apple Watch Series 3 tas viss ir pa rokai. Trīs riņķi. Viens mērķis. Stand, Move un Exercise riņķi ir vizualizācija tam, kā un cik tu kusties ik dienu. Noskaidro, vai nesēdi par daudz. Nosaki, cik kaloriju sadedzināji. Piefiksē, cik minūtes velti sportam. Vari pat lepni atrādīt savus riņķus draugiem. Izmēģini jaunās aktivitātes sacensības un saņem uzmundrinājumus no gudrās treniņu sistēmas, kad tev tie visvairāk vajadzīgi. Fiksē sasniegto tādās populārās nodarbēs kā joga, riteņbraukšana, peldēšana un augstas intensitātes intervāla treniņi.1 Fiksē datus par skrējieniem ar tādām mūsdienīgām funkcijām kā kadence un paziņojumi par tempu. Savieno savu pulksteni ar saderīgu sporta zāles aprīkojumu – bez kādiem vadiem.2 Un sinhronizē mīļāko atskaņošanas sarakstu no Apple Music, lai rokas nekad nenolaistos.',
    },
    {
        name: 'Apple Watch Series 6 GPS Space Gray',
        category: 'Viedpulksteņi',
        image: '/images/appw1.jpg',
        price: 459,
        brand: 'Apple',
        rating: 0,
        numReviews: 0,
        countInStock: 16,
        description: 'GPS modelis ļauj veikt zvanus un atbildēt uz īsziņām no plaukstas locītavas. Izmēriet skābekļa līmeni asinīs, izmantojot pilnīgi jaunu sensoru un lietotni. Pārbaudiet sirds ritmu, izmantojot EKG lietotni. Always-On Retina displejs ārā ir 2,5 reizes gaišāks, kad plaukstas locītava ir nolaista. S6 SiP ir līdz pat 20% ātrāks nekā 5. sērija 5GHz Wi-Fi un U1 Ultra Wideband mikroshēma. Izsekojiet savas ikdienas aktivitātes pakalpojumā Apple Watch un skatiet savas tendences iPhone lietotnē Fitness. Izmēriet tādus treniņus kā skriešana, pastaigas, riteņbraukšana, joga, peldēšana un dejas. Peldēšanas necaurlaidīgs dizains. Sinhronizējiet savu iecienīto mūziku, aplādes un audiogrāmatas.',
    },
    {
        name: 'Xiaomi Redmi Note 8 Pro 128GB Dual Mineral Grey',
        category: 'Viedtālruņi',
        image: '/images/xi1.jpg',
        price: 204,
        brand: 'Xiaomi',
        rating: 0,
        numReviews: 0,
        countInStock: 20,
        description: 'Nodrošina augstas izšķirtspējas fotogrāfijas plakātu drukāšanai līdz pat 3,26 m augstumam 64MP īpaši augstas izšķirtspējas kamera Gandrīz divreiz lielāks par 8K izšķirtspējas pikseļu skaitu* 25 reizes vairāk displeja pikseļu. Tuviniet, lai visu redzētu ļoti detalizēti. Atbalsta 4K video ierakstīšanu. Lēna kustība (960 kadri sekundē). Uzņemiet detaļas ar makro objektīvu Makro objektīvs ļaus fotografēt 2 cm attālumā. Pārsteidzošas autofokusa iespējas. 1,3 reizes plašāka redzamība * 120 ° īpaša platleņķa objektīvs ar deformāciju korekciju: vienā kadrā uzņem visu ainavu Ieslēdzot īpaša platleņķa režīmu, redzes lauks tiek mainīts no 79 ° uz 120 °, un jūs varat uzņemt vairāk ainu, nemainot fotografēšanas pozīciju. Spēļu procesors ar LiquidCool tehnoloģiju I Wi-Fi X antena I Slepenais ierocis profesionāliem spēlētājiem',
    },
    {
        name: 'Microsoft Xbox Series X 1TB',
        category: 'Spēļu konsoles',
        image: '/images/xboxx.jpg',
        price: 799,
        brand: 'Microsoft',
        rating: 0,
        numReviews: 0,
        countInStock: 11,
        description: 'Spēles, kas veidotas, izmantojot Xbox Series X | S izstrādes komplektu, ievērojami samazina ielādes laiku un satriecošus attēlus ar ātrumu līdz 120 kadriem sekundē. * Izmantojot viedo piegādi, jūs varat vienreiz iegādāties atbalstītu spēli, un jums vienmēr ir vislabākā pieejamā versija jebkurai konsolei, kurā spēlējat. Sākot no nākotnes piedzīvojumiem, līdz pat pašreizējām apsēstībām, līdz klasiskajiem nosaukumiem, tūkstošiem izlases četrās Xbox paaudzēs vislabāk izskatās un spēlē Xbox X sērijā. Sistēmā mikroshēmā (SOC) izvietotie 12 apstrādes jaudas 12 teraflops darbojas ar AMD Zen 2 un RDNA 2 arhitektūru, lai radītu pasaules, kas prasa rūpīgāku izskatu. Aprīkots ar AMD Zen 2 un RDNA 2 arhitektūru, DirectX staru izsekošana nodrošina patiesu apgaismojumu, ēnas un precīzus atstarojumus, lai radītu dinamisku, dzīvo pasauli. 3D telpiskā skaņa ir nākamā audio tehnoloģiju attīstība, izmantojot progresīvus algoritmus, lai radītu visaptverošu dzīvi, piemēram, pasaules, kas liek jums būt jūsu pieredzes centrā. Kopā jaunā mikroshēmas (SOC) sistēma un Xbox Velocity Architecture nodrošina ātrumu pa rokai, un 1 TB pielāgotais SSD un centrālais procesors nodod riteni jūsu rokās, lai jūs varētu pāriet no 0 līdz 60 līdz pat 120 kadriem sekundē.',
    },
    {
        name: 'Spēļu konsole Nintendo Switch',
        category: 'Spēļu konsoles',
        image: '/images/nintendo.jpg',
        price: 348,
        brand: 'Nintendo',
        rating: 0,
        numReviews: 0,
        countInStock: 14,
        description: 'Viens vai divi kontrolieri, vertikāli vai uz sāniem, kustības vadības pogas vai pogas ... Joy-Con un Nintendo Switch nodrošina jums pilnīgu spēles elastību. Spēles atdzīvojas, izmantojot ērti lietojamas kustības vadības ierīces un HD dārdoņu - uzlabotas vibrācijas funkcijas, kas iebūvētas katrā Joy-Con. Izmantojiet komplektācijā iekļauto rokturi Joy-Con, lai apvienotu abus Joy-Con tradicionālā stila kontrolieros. Atkarībā no spēles, jūs varat izmantot vienu Joy-Con katrā rokā vai pat nodot otro draugam. Gatavs doties? Bīdiet Joy-Con Nintendo slēdzī, lai tas būtu pārnēsājams. Dalieties jautrībā Sāciet spēļu ballīti jebkurā laikā, izmantojot Nintendo Switch * daudzspēlētāju spēles. Izmantojiet papildu Joy-Con kontrollerus, Nintendo Switch Pro kontrolierus vai abu kombināciju. Mājās sacensties ar draugiem (vai komandu). Spēlējiet tiešsaistē kopā ar citiem Nintendo Switch spēlētājiem. Saistiet līdz astoņām sistēmām, lai spēlētu jebkur. * Vairāku spēlētāju režīmiem nepieciešami papildu Joy-Con vai Nintendo Switch Pro kontrolieri; nopērkams atsevišķi. Vairāku spēlētāju funkcijas atšķiras atkarībā no spēles; sīkāku informāciju skatiet atsevišķās spēlēs.',
    },
    {
        name: 'Microsoft Xbox Series S 500GB',
        category: 'Spēļu konsoles',
        image: '/images/xbox_s.jpg',
        price: 449,
        brand: 'Microsoft',
        rating: 0,
        numReviews: 0,
        countInStock: 8,
        description: 'Nākamā spēļu paaudze nodrošina mūsu līdz šim lielāko digitālo palaišanas bibliotēku mūsu mazākajā Xbox. Ar dinamiskāku pasauli, ātrāku ielādes laiku un Xbox Game Pass pievienošanu (nopērkams atsevišķi) pilnībā digitālā Xbox S sērija ir vislabākā spēļu vērtība. Spēles, kas veidotas, izmantojot Xbox Series X | S izstrādes komplektu, ievērojami samazina ielādes laiku un satriecošus attēlus ar ātrumu līdz 120 kadriem sekundē. Izmantojot viedo piegādi, jūs varat vienreiz iegādāties atbalstītu spēli, un jums vienmēr ir vislabākā pieejamā versija jebkurai konsolei, kurā spēlējat. Neatkarīgi no tā, vai meklējat vienas dienas palaišanas nosaukumu, kādu no simts izlases Xbox Game Pass bibliotēkā vai kādu no tūkstošiem savietojamu klasiku, vienmēr ir kaut kas, ko spēlēt digitālajā Xbox S sērijā.',
    },
    {
        name: 'Sony PlayStation 4 (PS4) Pro 1TB Black',
        category: 'Spēļu konsoles',
        image: '/images/pspro.jpg',
        price: 449,
        brand: 'Sony',
        rating: 0,
        numReviews: 0,
        countInStock: 7,
        description: 'Dinamiskas 4K spēles un 4K izklaide * Iespaidīga grafika Izpētiet spilgtas spēļu pasaules ar bagātīgu vizuālo izskatu, ko pastiprina PS4 Pro. ** Uzlabots spēlēšanas atbalsts ātrākam kadru ātrumam nodrošina īpaši asu darbību atsevišķām PS4 ™ spēlēm. ** Vienota spēļu kopiena, kas ir saderīga ar katru PS4 ™ spēli. Spēlējiet tiešsaistē ar citiem PS4 ™ atskaņotājiem, izmantojot PlayStation® Plus. *** Ārkārtas izklaide Ar līdz pat 4K straumēšanu un 4K automātisku video satura palielināšanu. **** PS4 Pro izvada spēļu izšķirtspēju no 1080p līdz 1440p. PS4 Pro izmanto uzlabotas izšķirtspējas metodes, lai palielinātu spēles izšķirtspēju, lai tuvotos 4K. PS4 Pro nodrošina spēļu izšķirtspējas izvadi ar vietējo 2160p izšķirtspēju. Uzlabota objektu redzamība tālāk fonā ar lielāku fokusu un detalizētāku izklāstu. Attēli ar mīkstām funkcijām, piemēram, noapaļotiem stūriem un sejām, šķiet vienmērīgāki un vizuāli reālistiskāki. Vizuāliem ar ļoti mazām funkcijām, piemēram, dūmiem un tvaikam, ir smagāks izskats un reālistiska izjūta. PS4 Pro ļauj sarežģītāk noformēt attēlus, kas rada tādu detaļu, kādu mēs redzam spēlēs, piemēram, netīrumi uz apģērba vai rūsas uz metāla. PS4 Pro nodrošina asākas ēnas ar tīrākām detaļām lielākā attālumā, radot dziļumu un attēla kontekstu. PS4 Pro parāda sarežģītākus attēlus, vienlaikus palielinot ekrānā esošo attēlu daudzumu. HDR līdzsvaro spēles gaismu, tuvojoties visam gaismas spektram, ko redzam ar cilvēka aci (pieejams arī bāzes modelī PS4). PS4 Pro nodrošina ātrāku mērķtiecīgu kadru ātrumu vai vienmērīgāku bloķētu kadru ātrumu.',
    },
    {
        name: 'Televizors Philips 55PUS7805/12 LED',
        category: 'Televizori',
        image: '/images/tv1.jpg',
        price: 448,
        brand: 'Philips',
        rating: 0,
        numReviews: 0,
        countInStock: 8,
        description: 'Dolby Vision un Dolby Atmos. Kinoteātra cienīgs attēls un skaņa. Atbalsts Dolby augstās kvalitātes skaņas un video formātiem nozīmē, ka HDR saturs izskatīsies un izklausīsies neticami īsti. Vai nu jaunākie straumēšanas seriāli vai Blu-Ray disku komplekts, izbaudīt varēsiet kontrastu, spilgtumu un krāsas, kas atspoguļo režisora oriģinālo ieceri. Kā arī telpu piepildīs skaidra, niansēta un dziļa skaņa. Philips P5 dzinis. Ideāls rezultāts neatkarīgi no avota. Philips P5 Perfect Picture dzinis nodrošina perfekti dzidrus attēlus, kas ir tikpat izcili, kā jūsu iecienītais saturs. Ievērojami lielāks detalizācijas dziļums, izteiksmīgas krāsas un dabiski ādas toņi. Nepārspējami dzidrais kontrasts ļauj jums izbaudīt ikvienu attēla detaļu. Videoattēls ir vienmērīgs, ļaujot jums nezaudēt bumbu skatienam, neatkarīgi no spēles straujuma un intensitātes. Piekļuve lietotnēm, piemēram, Netflix un Prime Video, ar vienu pogas spiedienu. SAPHI ir ātra un intuitīva operētājsistēma, kas pārvērš jūsu Philips Smart TV lietošanu patiesā baudījumā. Baudiet izcilu attēla kvalitāti un piekļūstiet izvēlnei ar skaidri saprotamām ikonām, nospiežot tikai vienu pogu. Izbaudiet sava televizora lietošanas ērtumu un izmantojiet populārākās Philips Smart TV lietotnes, tostarp YouTube, Netflix un Amazon Prime Video. Ambilight maģija. Tikai no Philips. Ar Philips Ambilight ikviens brīdis šķiet tuvāks. Inteliģentās gaismu diodes apkārt televizora malai reaģē uz darbību ekrānā un izstaro visaptverošu mirdzumu, kas pilnībā apbur. Pietiek to vienreiz pieredzēt, lai prātotu, kā pirms tam varējāt baudīt televizora skatīšanos. Phillips "4K UHD TV". Dinamisks HDR attēls. Jūsu Philips 4K UHD televizors ir saderīgs ar visiem galvenajiem HDR formātiem, tajā skaitā HDR10+ un Dolby Vision. Dziļākas ēnas būs redzamas gan jaunākajos seriālos, gan videospēlēs. Spilgtas virsmas spīdēs. Krāsas būs dzīvākas.',
    },
    {
        name: 'Televizors LG 49NANO813NA',
        category: 'Televizori',
        image: '/images/tv2.jpg',
        price: 531,
        brand: 'LG',
        rating: 0,
        numReviews: 0,
        countInStock: 17,
        description: 'Tīras RGB krāsas ir kvalitatīva, reālistiska attēla priekšnoteikums. NanoCell tehnoloģija izmanto nanodaļiņas, kas attīra krāsas, atfiltrējot blāvās krāsas un uzlabojot RGB spektra tīrību.NanoCell televizors atveido reālu 4K izšķirtspēju, kas atbilst starptautiskajos standartos noteiktajām CM vērtībām. Atklājiet košākus un skaidrākus attēlus ar reālu 4K izšķirtspēju, kuru papildina NanoCell tehnoloģija. NanoCell televizora četrkodolu procesors novērš troksni attēlos un ļauj atveidot dinamiskākas krāsas un kontrastu. Zemas izšķirtspējas attēliem tiek palielināta izšķirtspēja, un tie tiek attēloti gandrīz 4K kvalitātē. NanoCell televizors visas ainas padara reālistiskas, pateicoties košajām, tīrajām krāsām un nanomelnās krāsas radītajam izteiktajam kontrastam. Turklāt tas nodrošina optimizētu attēlu un skaņu, radot pasakainu, reālistiskāku skatīšanās pieredzi. Ar NanoCell televizoru tagad ir iespēja radīt patiesu mājas kinozāli ar neierobežotām izklaidēm.',
    },



],
};
export default data;