const data = {
    products:[
    {
        _id: '1',
        name: 'iPhone X',
        category: 'Viedtālruņi',
        image: '/images/2.jpg',
        price: 949,
        rating: 4.8,
        numReviews: 15,
        countInStock: 0,
        description: 'testtesttesttesttesttesttesttest',
    },
    {
        _id: '2',
        name: 'iPhone 8',
        category: 'Televizori',
        image: '/images/2.jpg',
        price: 399,
        rating: 4.3,
        numReviews: 15,
        countInStock: 3,
        description: 'testtesttesttesttesttesttesttest',
    },
    {
        _id: '3',
        name: 'iPhone 11 Pro Max',
        category: 'Veļasmašīnas',
        image: '/images/1.jpg',
        price: 1199,
        rating: 3.2,
        numReviews: 15,
        countInStock: 10,
        description: 'testtesttesttesttesttesttesttest',
    },
    {
        _id: '4',
        name: 'iPhone 11 Pro Max',
        category: 'Veļasmašīnas',
        image: '/images/1.jpg',
        price: 1199,
        rating: 5,
        numReviews: 15,
        countInStock: 15,
        description: 'testtesttesttesttesttesttesttest',
    },
],
};
export default data;